Shop.UI/Controllers/Admin/OrdersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Admin.OrdersAdmin;

namespace Shop.UI.Controllers.Admin
{
    [Route("[controller]")]
    [Authorize(Policy = "Manager")]
    public class OrdersController : Controller
    {
        [HttpGet("")]
        public IActionResult GetOrders(int status,
            [FromServices] GetOrders getOrders) => 
            Ok(getOrders.Do(status));

        [HttpGet("{id}")]
        public IActionResult GetOrder(int id,
            [FromServices] GetOrder getOrder) => 
            Ok(getOrder.Do(id));

        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateOrder(int id,
            [FromServices] UpdateOrder updateOrder) => 
            Ok(await updateOrder.Do(id));
    }
}

Shop.UI/Controllers/Admin/ProductsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Admin.ProductsAdmin;
using Shop.Database;

namespace Shop.UI.Controllers.Admin
{
    [Route("[controller]")]
    [Authorize(Policy = "Manager")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _ctx;
        private readonly IWebHostEnvironment _env;

        public ProductsController(ApplicationDbContext ctx, IWebHostEnvironment env)
        {
            _ctx = ctx;
            _env = env;
        }

        [HttpGet("")]
        public IActionResult GetProducts() => Ok(new GetProducts(_ctx).Do());

        [HttpGet("{id}")]
        public IActionResult GetProduct(int id) => Ok(new GetProduct(_ctx).Do(id));

        [HttpPost("")]
        public async Task<IActionResult> CreateProduct([FromForm] CreateProduct.Request request) => Ok((await new CreateProduct(_ctx, _env).Do(request)));

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteProduct(int id) => Ok((await new DeleteProduct(_ctx).Do(id)));

        [HttpPut("")]
        public async Task<IActionResult> UpdateProduct([FromForm] UpdateProduct.Request request) =>
            Ok((await new UpdateProduct(_ctx, _env).Do(request)));
    }
}

Shop.UI/Controllers/OrdersController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Shop.Application.Admin.OrdersAdmin;

namespace Shop.UI.Controllers
{
    [Route("[controller]")]
    [Authorize(Policy = "Manager")]
    public class OrdersController : Controller
    {
        [HttpGet("")]
        public IActionResult GetOrders(int status,
            [FromServices] GetOrders getOrders) => 
            Ok(getOrders.Do(status));

        [HttpGet("{id}")]
        public IActionResult GetOrder(int id,
            [FromServices] GetOrder getOrder) => 
            Ok(getOrder.Do(id));

        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateOrder(int id,
            [FromServices] UpdateOrder updateOrder) => 
            Ok(await updateOrder.Do(id));
    }
}

Shop.UI/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Database;
using Shop.Application.Products;

namespace Shop.UI.Controllers
{
    [Route("")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _ctx;

        public ProductsController(ApplicationDbContext ctx)
        {
            _ctx = ctx;
        }

        [HttpGet("")]
        public IActionResult GetProducts() => Ok(new GetProducts(_ctx).Do());
    }
}

Shop.UI/Pages/Cart.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.Cart;

namespace Shop.UI.Pages
{
    public class CartModel : PageModel
    {
        public IEnumerable<GetCart.Response> Cart { get; set; }

        public IActionResult OnGet([FromServices] GetCart getCart)
        {
            Cart = getCart.Do();

            return Page();
        }
    }
}

Shop.UI/Pages/ConfirmPage.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Domain.Models;

namespace Shop.UI.Pages
{
    [ValidateAntiForgeryToken]
    public class ConfirmPageModel : PageModel
    {
        public async Task <IActionResult> OnGetAsync([FromServices] UserManager<User> userManager,string userId, string code)
        {
            var user = await userManager.FindByIdAsync(userId);

            if (user == null)
                return RedirectToPage("Error");

            var result = await userManager.ConfirmEmailAsync(user, code);

            if (result.Succeeded)
                return Page();

            return RedirectToPage("Error");
        }
    }
}

Shop.UI/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Shop.UI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Shop.UI/Pages/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.Categories;
using Shop.Application.Products;
using Shop.Database;
using SmartBreadcrumbs.Attributes;

namespace Shop.UI.Pages
{
    [DefaultBreadcrumb("Главная")]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _ctx;
        private readonly IEnumerable<GetProducts.ProductViewModel> _products;
        public IndexModel(ApplicationDbContext ctx, IEnumerable<GetProducts.ProductViewModel> products)
        {
            _ctx = ctx;
            _products = products;
        }
        public IEnumerable<GetProducts.ProductViewModel> Products { get; set; }

        [BindNever]
        public IEnumerable<GetProducts.ProductViewModel> ProductsFromCategory { get; set; }

        public IEnumerable<GetCategories.CategoryViewModel> Categories { get; set; }
        [BindProperty(SupportsGet = true)]
        public string Name { get; set; }

        public void OnGet(int categoryId)
        {
            Categories = new GetCategories(_ctx).Do();
            Products = new GetProducts(_ctx).Do();
            ProductsFromCategory = new GetProducts(_ctx).ProductsFromCategory(categoryId);

            if (ProductsFromCategory != null)
            {
                Products = ProductsFromCategory;
            }
            else
            {
                Products = Name == null ? new GetProducts(_ctx).Do() : new GetProducts(_ctx).Do(Name);
            }
        }

        public void OnPost()
        {
            if (_products.Count() != 0)
                Products = _products;
        }

        public void OnPostCategoriesProducts(List<int> categoryId)
        {
            Products = new GetProducts(_ctx).Do(categoryId);
            Categories = new GetCategories(_ctx).Do();
            RedirectToPage("/Index");
        }

        public void OnPostSearchProducts(string name)
        {
            Products = new GetProducts(_ctx).Do(name);
            Categories = new GetCategories(_ctx).Do();
            RedirectToPage("/Index");
        }
    }
}

Shop.UI/Pages/Order.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.Orders;
using Shop.Database;

namespace Shop.UI.Pages
{
    public class OrderModel : PageModel
    {
        private readonly ApplicationDbContext _ctx;

        public OrderModel(ApplicationDbContext ctx)
        {
            _ctx = ctx;
        }

        public GetOrder.Response Order { get; set; }

        public void OnGet(string reference)
        {
            Order = new GetOrder(_ctx).Do(reference);
        }
    }
}

Shop.UI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Shop.UI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Shop.UI/Pages/Product1.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Shop.Application.Cart;
using Shop.Application.Products;
using Shop.Database;
using SmartBreadcrumbs.Attributes;

namespace Shop.UI.Pages
{
    [Breadcrumb("ViewData.Title")]
    public class Product1Model : PageModel
    {
        private readonly ApplicationDbContext _ctx;

        public Product1Model(ApplicationDbContext ctx)
        {
            _ctx = ctx;
        }

        [BindProperty(SupportsGet = true)]
        public AddToCart.Request CartViewModel { get; set; }

        public GetProduct.ProductViewModel Product { get; set; }


        public async Task<IActionResult> OnGet(string name)
        {
            Product = await new GetProduct(_ctx).Do(name.Replace("-", " "));

            if (Product == null)
                return RedirectToPage("Index");
            else
            {
                ViewData["Title"] = Product.Name;

                return Page();
            }
        }

        public async Task<IActionResult> OnPost([FromServices] AddToCart addToCart, string name)
        {
            Product = await new GetProduct(_ctx).Do(name.Replace("-", " "));
            ViewData["Title"] = Product.Name;
            var stockAdded = await addToCart.Do(CartViewModel);

            if (stockAdded)
                return RedirectToPage("Cart");
            else
                return Page();
        }
    }
}

Shop.UI/Pages/VerifyEmail.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Shop.UI.Pages
{
    public class VerifyEmailModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Shop.UI/Pages/Cart.cshtml
@page
@model Shop.UI.Pages.CartModel
@{
}


@*<div class="container">
    <div class="columns">
        <partial name="_CartPartial1" model="@Model.Cart" />
    </div>
</div>*@

<partial name="Shared/_CartPartial1" model="@Model.Cart"/>

@section scripts{

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <script>
        var addOneToCart = function (e) {
            var stockId = e.target.dataset.stockId;

            axios.post("/Cart/AddOne/" + stockId)
                .then(res => {
                    updateCart();
                })
                .catch(err => {
                    alert(err.error);
                });
        }

        var removeOneFromCart = function (e, qty) {
            var stockId = e.target.dataset.stockId;
            removeFromCart(stockId, 1);
        }

        var removeAllFromCart = function (e) {
            var stockId = e.target.dataset.stockId;
            var id = "stock-qty-" + stockId;
            var el = document.getElementById(id);
            var qty = parseInt(el.innerText);
            removeFromCart(stockId, qty);
        }

        var removeFromCart = function (stockId, qty) {
            axios.post("/Cart/Remove/" + stockId + '/' + qty)
                .then(res => {
                    updateCart();
                })
                .catch(err => {
                    alert(err.error);
                });
        }

        var updateCart = function () {
            axios.get('/Cart/GetCartComponent')
                .then(res => {
                    var html = res.data;
                    var el = document.getElementById('cart-nav');

                    el.outerHTML = html;
                });

            axios.get('/Cart/GetCartMain')
                .then(res => {
                    var html = res.data;
                    var el = document.getElementById('cart-main');

                    el.outerHTML = html;
                });
        }
    </script>
}

Shop.UI/Pages/ConfirmPage.cshtml
@page
@model Shop.UI.Pages.ConfirmPageModel

<h1 class="title">Вы успешно подтвердили вашу электронную почту</h1>
<h2>Войдите в свой аккаунт <a href="/Accounts/Login">Войти</a></h2>

Shop.UI/Pages/EditData.cshtml
@page
@model Shop.UI.Pages.EditDataModel
@{
}

<form method="post">

    <div class="field">
        <p class="control">
            <label class="label">Имя</label>
            <input class="input" type="text" asp-for="User.Name" value="@Model.User.Name" />
        </p>
    </div>

    <div class="field">
        <p class="control">
            <label class="label">Фамилия</label>
            <input class="input" type="text" asp-for="User.SurName" value="@Model.User.SurName" />
        </p>
    </div>

    <div class="field">
        <p class="control">
            <label class="label">Отчество</label>
            <input class="input" type="text" asp-for="User.Patronymic" value="@Model.User.Patronymic" />
        </p>
    </div>

    <div class="field">
        <p class="control">
            <label class="label">Почта</label>
            <input class="input" type="text" asp-for="User.Email" value="@Model.User.Email" />
        </p>
    </div>
    
    <div class="field">
        <p class="control">
            <label class="label">Номер телефона</label>
            <input class="input" type="tel" asp-for="User.Phone" value="@Model.User.Phone"/>
        </p>
    </div>

    <input class="btn btn-primary" type="submit" value="Изменить" />

</form>

Shop.UI/Pages/EditPassword.cshtml
@page
@model Shop.UI.Pages.EditPasswordModel
@{
}

<h2>Изменение пароля</h2>

<form method="post">
    <div class="field">
        <p class="control">
            <label class="label">Старый пароль</label>
            <input class="input" asp-for="ChangePasswordModel.OldPassword" />
        </p>
    </div>

    <div class="field">
        <p class="control">
            <label class="label">Новый пароль</label>
            <input class="input" asp-for="ChangePasswordModel.NewPassword" />
        </p>
    </div>

    <div class="field">
        <p class="control">
            <label class="label">Подтверждение нового пароля</label>
            <input class="input" asp-for="ChangePasswordModel.ConfirmNewPassword" />
        </p>
    </div>

    <input type="submit" value="Изменить" />
</form>

Shop.UI/Pages/ForgotPassword.cshtml
@page
@model Shop.UI.Pages.ForgotPasswordModel
@{
    ViewData["Title"] = "Восстановление пароля";
}

<h2 class="title">@ViewData["Title"]</h2>
<form method="post">
    <div class="column">
        <div class="column is-6">
            <div class="field has-addons">
                <div class="control is-expanded">
                    <input class="input" type="email" placeholder="Введите email" asp-for="Model.Email"/>
                </div>
                <div class="control">
                    <button class="button is-success" type="submit">
                        Отправить
                    </button>
                </div>
            </div>

        </div>
    </div>
</form>

Shop.UI/Pages/Index.cshtml
@page "{categoryId?}"
@model IndexModel
@{
    ViewData["Title"] = "Главная страница";
}

<div class="shop-category-area pt-100px pb-100px">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 order-lg-first col-md-12 order-md-first order-1 mb-md-60px mb-lm-60px">
                <div class="shop-sidebar-wrap">

                    <div class="sidebar-widget-search">
                        <form method="post" asp-page-handler="SearchProducts" id="widgets-searchbox">
                            <input class="input-field" type="text" placeholder="Поиск" name="name">
                            <button class="widgets-searchbox-btn" type="submit">
                                <i class="fa fa-search"></i>
                            </button>
                        </form>
                    </div>

                    <div class="sidebar-widget">
                        <h4 class="sidebar-title">Категории</h4>
                        <div class="sidebar-widget-category">
                            <form method="post" asp-page-handler="CategoriesProducts">
                                @foreach (var parent in Model.Categories.Where(x => x.ParentCategoryId == null))
                                {
                                    <label class="text-lg-center">@parent.Title</label>
                                    <div class="select">
                                        <select name="categoryId">
                                            <option value="hide">--Выберите категорию</option>
                                            @foreach (var child in Model.Categories.Where(x => x.ParentCategoryId == parent.Id))
                                            {
                                                <option name="categoryId" value="@child.Id">@child.Title</option>
                                            }
                                        </select>
                                    </div>
                                }
                                <button class="btn btn-primary" type="submit">Выбрать</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-9 order-lg-last col-md-12 order-md-last order-2">
                @*<div class="shop-top-bar d-flex">
                    <div class="select-shoing-wrap d-flex align-items-center">
                        <div class="shot-product">
                            <p>Сортировать по:</p>
                        </div>
                        <div class="shop-select">
                            <select class="shop-sort">
                                <option data-display="Relevance">Relevance</option>
                                <option value="1"> Имени, от А до Я</option>
                                <option value="2"> Имени, от Я до А</option>
                                <option value="3"> Цене, от меньшей к большей</option>
                                <option value="4"> Цене, от большей к меньшей</option>
                            </select>

                        </div>
                    </div>
                </div>*@
                <div class="shop-bottom-area">
                    <div class="row">
                        <div class="col">
                            <div class="tab-content">
                                <div class="tab-pane fade show active" id="shop-grid">
                                    <div class="row mb-n-30px">
                                        @for (int i = 0; i < 5; i++)
                                        {
                                            @foreach (var product in Model.Products)
                                            {
                                                <div class="col-lg-4 col-md-6 col-sm-6 col-xs-6 mb-30px" data-aos="fade-up"
                                                     data-aos-delay="200">
                                                    <div class="product">
                                                        <div class="thumb">
                                                            <a asp-page="Product1" asp-route-name="@product.Name.Replace(" ", "-")" class="image">
                                                                <img src="@Url.Content("/images/"+product.Image.FirstOrDefault())" />
                                                            </a>
                                                        </div>
                                                        <div class="content">
                                                            <div>
                                                                @{
                                                                    string cssClass = "";
                                                                    string message = "";
                                                                    if (product.StockCount == 0)
                                                                    {
                                                                        cssClass = "text-danger";
                                                                        message = "Нет на складе";
                                                                    }
                                                                    else if (product.StockCount <= 10)
                                                                    {
                                                                        cssClass = "text-warning";
                                                                        message = "Осталось совсем чуть-чтуь";
                                                                    }
                                                                }
                                                                @if (product.StockCount <= 10)
                                                                {
                                                                    <div class="notification is-paddingless has-text-centered @cssClass">
                                                                        @message
                                                                    </div>
                                                                }
                                                            </div>
                                                            <h5 class="title">
                                                                <a asp-page="Product" asp-route-name="@product.Name.Replace(" ", "-")">
                                                                    @product.Name
                                                                </a>
                                                            </h5>
                                                            <span class="price">
                                                                <span class="new">$38.50</span>
                                                            </span>
                                                        </div>
                                                    </div>
                                                </div>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Shop.UI/Pages/Order.cshtml
@page "{reference}"
@model Shop.UI.Pages.OrderModel
@{
}


<div>
    <h1>
        @Model.Order.OrderRef
    </h1>
    
    @foreach (var product in Model.Order.Products)
    {
        <div>
            @product.Name - @product.Description - @product.Qty - @product.Value
        </div>
    }
</div>

Shop.UI/Pages/Product.cshtml
@page "{name}"
@model Shop.UI.Pages.ProductModel
@{
}

<link href="~/css/accordion-style.css" rel="stylesheet" />

<div class="hero">
    <div class="hero-body">
        <div class="container">
            <div class="columns">
                <div class="column is-6">
                    <figure class="image">
                        <img src="/products/images/@Model.Product.Image"/>
                    </figure>
                </div>
                <div class="column is-6">
                    <section class="content">
                        @*<p class="subtitle">@Model.Product.Description</p>
                            <p>Категории</p>
                        @foreach (var category in Model.Product.Categories)
                        {
                            <p class="content">
                                @category.Category.Title
                            </p>
                        }*@
                        <header>
                            <p class="title">@Model.Product.Name</p>
                        </header>
                        <main>
                            <p class="has-text-weight-bold">Цена: @Model.Product.Value</p>
                        </main>
                        <footer>
                            <form method="post">
                                <div class="field is-horizontal">
                                    <div class="field-label is-normal">
                                        <label class="label">Размер</label>
                                    </div>
                                    <div class="field-body">
                                        <div class="field is-narrow">
                                            <div class="control">
                                                <div class="select is-fullwidth">
                                                    <select asp-for="CartViewModel.StockId" onchange="toggleStock(event)">
                                                        <option disabled="disabled" selected="selected">Выберите размер</option>
                                                        @foreach (var stock in Model.Product.Stock)
                                                        {
                                                            bool disabled = stock.Qty <= 0;

                                                            <option id="qtyProduct-@stock.Qty" value="@stock.Id" disabled="@disabled">@stock.Description</option>
                                                        }

                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="field is-horizontal">
                                    <div class="field-label is-normal">
                                        <label class="label">Количество</label>
                                    </div>
                                    <div class="field-body">
                                        <div class="field is-narrow">
                                            <div class="control">
                                                <input class="input" asp-for="CartViewModel.Qty" value="1" min="1" id="inputQty" />
                                            </div>

                                            @foreach (var stock in Model.Product.Stock)
                                            {
                                                if (stock.Qty <= 100)
                                                {
                                                    <p class="help is-danger is-hidden low-stock" id="low-stock-@stock.Id">
                                                        @(stock.Qty == 0 ? "Нет на складе" : $"{stock.Qty} осталось")
                                                    </p>
                                                }
                                            }
                                            @ViewData["EnoughQty"]
                                        </div>
                                    </div>
                                </div>
                                <div class="field is-horizontal">
                                    <div class="field-label is-normal">
                                    </div>
                                    <div class="field-body">
                                        <div class="field is-narrow">
                                            <div class="control">
                                                <button class="button is-success" type="submit">Добавить в корзину</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </footer>

                        <div class="accordion1">

                            <div>
                                <input type="radio" name="accordion" id="section-description" class="accordion1__input" />
                                <label for="section-description" class="accordion1__label">Описание товара</label>
                                <div class="accordion1__content">
                                    <p>
                                        @Model.Product.Description
                                    </p>
                                </div>
                            </div>

                            <div>
                                <input type="radio" name="accordion" id="section-structure" class="accordion1__input" />
                                <label for="section-structure" class="accordion1__label">Состав товара</label>
                                <div class="accordion1__content">
                                    <p>
                                        @Model.Product.Description
                                    </p>
                                </div>
                            </div>

                        </div>

                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var toggleStock = function (e) {
        console.log(e.target.value.qty);
        console.log(e.target.value);

        var stockToHide = document.querySelectorAll('.low-stock');
        var inputForQty = document.getElementById('inputQty');

        //console.log(stockToHide);
        //console.log(inputForQty);

        inputForQty.max = 13;

        stockToHide.forEach(function (e) {
            e.classList.add('is-hidden');
        });

        showLowStock(e.target.value);
    };

    var showLowStock = function (id) {
        var stockToShow = document.getElementById('low-stock-' + id);

        if (stockToShow !== null && stockToShow !== undefined)
            stockToShow.classList.remove('is-hidden');
    };

    showLowStock(document.getElementById('CartViewModel_StockId').value);

    @*function qtyProducts(input) {
        var stockId = document.getElementById('qtyProduct-' + id);

        input.max = @Model.Product.Stock.FirstOrDefault(x => x.Id == 3).Qty;

        console.log(stockId);
    }*@

    function isQty(obj) {
        if (obj.value > 5) obj.value = obj.max;
        else obj.max = 3;
    }
</script>

Shop.UI/Pages/VerifyEmail.cshtml
@page
@model Shop.UI.Pages.VerifyEmailModel
@{
}

<div class="blank-page-area pb-100px pt-100px">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <div class="blank-content-header ">
                    <h1>Письмо с подтверждением отправлено на вашу электронную почту.</h1>
                </div>
            </div>
        </div>
    </div>
</div>